### PR TITLE
try python version 3.12

### PR DESCRIPTION
**Pull request by jonathf**
Solves #101.

### CODE REVIEW

**Comment by nilsnolde** [comment]
FWIW, the doctest failure makes sense, we recently added different data to Valhalla which makes the durations quite a bit longer.

**Comment by jonathf** [comment]
Yeah, I doubted that had anything to do with this patch. I am rerunning the a new tag on current main to see if the Windows failure are connected.

Nils, you added the 3.12 restriction. Do you remember why, and if we can expect it to resolve it self now that 3.12 is out stable?

**Comment by nilsnolde** [comment]
Yeah I’m pretty sure that was only because it wasn’t release yet, but it was built by default. In fact I think 3.12 introduced ABI stability in between minor versions, so in uhh, 5 years from now (?) we can stop building all of them;)

**Comment by jonathf** [comment]
@jcoupey, we have a small issue.

PyPI which hosts all python packages have started to require deploy tokens for publishing. I don't seem to have the rights to add Github secrets to so we can use it with Github actions.

We have a few options I think:

1. Do you (or @nilsnolde ) want access to pyvroom om pypi so you can fix the deploy token issue?
2. Do you want me to create the token, and you add it?
3. If possible can I have access to adding secrets?

**Comment by jonathf** [comment]
Sure. How would you like the token sent over?

**Comment by jcoupey** [comment]
You can use the contact email on http://vroom-project.org.

**Comment by jcoupey** [comment]
Thanks, just updated the `pypi_password` secret with the token you sent. Let me know if there is anything else required.

**Comment by jonathf** [comment]
Looks like it works as intended. Thanks for the quick assist @jcoupey!

**Pull request merged**
