### PR TITLE
Enable windows support again

### PR DESCRIPTION
**Pull request by jonathf**

### CODE REVIEW

**Comment by nilsnolde** [comment]
this worked. I canceled the release actions. I wonder why they even started, I didn't publish any tag.. github being buggy again?

anyways, what do you think @jonathf ? should we look at merging the vroom PR to your repo before merging this so we can change the submodule again?

**Comment by jonathf** [comment]
No, sorry. I made the tag. I didn't see you triggering actions manually.
I'm looking at th code now.

**Comment by nilsnolde** [comment]
ha weird, never noticed that I don't get notified via email when someone tags. 

github's documentation is really fuzzy about it. I thought maybe it's also triggering on all branches by default. we can still leave it in for clarity I guess.

no stress reviewing, but thanks:)

**Comment by jonathf** [comment]
This is awesome. Thanks for doing this.

**Pull request merged**
